# Users & Auth
# Check token
GET http://localhost:5000/api/auth HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# Posts
GET http://localhost:5000/api/posts HTTP/1.1
###

# Get self profile
GET http://localhost:5000/api/profile/me HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# Get all profiles
GET http://localhost:5000/api/profile/ HTTP/1.1
###

# Create profile
POST http://localhost:5000/api/profile/ HTTP/1.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY

{
    "company":"IDF",
    "status":"Team Commander",
    "skills":"HTML,CSS,Python,JavaScript,Java,Node.js,React,Linux,Windows",
    "location":"Hod Hasharon, IL",
    "bio":"I am a Junior software developer",
    "githubusername":"omrigo312",
    "twitter":"https://twitter.com/omrigo312",
    "facebook":"https://facebook.com/omrigo312",
    "linkedin":"https://linkedin.comin/omri-goldstein/"
}
###

# Add experience to profile
PUT http://localhost:5000/api/profile/experience HTTP/1.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY

{
    "title":"Waiter",
    "company":"Ahuzat Hasharon",
    "location":"Hod Hasharon",
    "from":"7-9-2017",
    "to":"10-29-2017",
    "desctiption":"terrible"
}
###

# Delete experience from profile
DELETE http://localhost:5000/api/profile/experience/5f6a11d8fbe9ef1e609ff0d2 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# Add education to profile
PUT http://localhost:5000/api/profile/education HTTP/1.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY

{
    "school":"Ben Gurion University",
    "degree":"Bachelor's degree",
    "fieldofstudy":"Computer Science",
    "from":"7-9-2017"
}
###

# Delete education from profile
DELETE http://localhost:5000/api/profile/education/5f6a29cf4a3a582228de4b23 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# Get Github repositories
GET http://localhost:5000/api/profile/github/omrigo312
###

# Add post
POST http://localhost:5000/api/posts HTTP/1.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY

{
    "text":"My first post"
}
###

# Get all posts
GET http://localhost:5000/api/posts HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# Get post by id
GET http://localhost:5000/api/posts/5f6a3ccf680a961e10fc2d93 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# Delete post by id
DELETE http://localhost:5000/api/posts/5f6ba5c2cffd6129a477463a HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2N2Q3MmZjZTliOTcyYjljZDE5ZjFiIn0sImlhdCI6MTYwMDY0MDgxNSwiZXhwIjoxNjAxMDAwODE1fQ.ztur8Bzc7ArJvTWpcaiu6mGkIhi5tYlpYC_re4696uY
###

# register
POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Omri Goldstein",
    "email": "omrigo3122@gmail.com",
    "password": "omrigo312"
}
###

# login
POST http://localhost:5000/api/auth HTTP/1.1
content-type: application/json

{
    "email": "omrigo312@gmail.com",
    "password": "omrigo312"
}
###